import os
import re
from onion_manager import config
from onion_manager.utils.file_helpers import backup_file, safe_write


def create_default_torrc():
    geoip_path = os.path.join(config.BASE_DIR, 'data', 'geoip')
    geoip6_path = os.path.join(config.BASE_DIR, 'data', 'geoip6')
    content = f"""# torrc generated by Onion Manager
AvoidDiskWrites 1
Log notice stdout
CookieAuthentication 1
DormantCanceledByStartup 1
GeoIPFile {geoip_path}
GeoIPv6File {geoip6_path}
ClientTransportPlugin meek_lite,obfs2,obfs3,obfs4,scramblesuit,webtunnel exec {config.LYREBIRD_EXE}
ClientTransportPlugin snowflake exec {config.LYREBIRD_EXE}
ClientTransportPlugin conjure exec {config.CONJURE_EXE} -registerURL https://registration.refraction.network/api
ExcludeNodes {{ru}}, {{by}}, {{ua}}, {{kz}}
StrictNodes 1
UseBridges 1
HTTPTunnelPort 9051
SOCKSPort 9050

%include {config.BRIDGE_FILE}
"""
    os.makedirs(os.path.dirname(config.TORRC), exist_ok=True)
    backup_file(config.TORRC)
    safe_write(config.TORRC, content)


def fix_paths_in_torrc():
    if not os.path.exists(config.TORRC):
        create_default_torrc()
        return
    try:
        with open(config.TORRC, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        modified = False
        new_lines = []
        geoip = os.path.join(config.BASE_DIR, 'data', 'geoip')
        geoip6 = os.path.join(config.BASE_DIR, 'data', 'geoip6')
        for line in lines:
            if re.match(r'^\s*GeoIPFile\s', line, re.IGNORECASE):
                new_line = f"GeoIPFile {geoip}\n"
                if new_line != line:
                    modified = True
                new_lines.append(new_line)
            elif re.match(r'^\s*GeoIPv6File\s', line, re.IGNORECASE):
                new_line = f"GeoIPv6File {geoip6}\n"
                if new_line != line:
                    modified = True
                new_lines.append(new_line)
            elif re.search(r'lyrebird', line, re.IGNORECASE) and '.exe' in line.lower():
                new_line = re.sub(r'exec\s+[^\s]+', f"exec {config.LYREBIRD_EXE}", line, flags=re.IGNORECASE)
                if new_line != line:
                    modified = True
                new_lines.append(new_line)
            elif re.search(r'conjure-client', line, re.IGNORECASE):
                new_line = re.sub(r'exec\s+[^\s]+', f"exec {config.CONJURE_EXE}", line, flags=re.IGNORECASE)
                if new_line != line:
                    modified = True
                new_lines.append(new_line)
            elif re.match(r'^\s*%include\s', line, re.IGNORECASE):
                new_line = f"%include {config.BRIDGE_FILE}\n"
                if new_line != line:
                    modified = True
                new_lines.append(new_line)
            else:
                new_lines.append(line)
        # remove empty lines
        filtered = [l for l in new_lines if l.strip() != '']
        if filtered != new_lines:
            modified = True
            new_lines = filtered
        if modified:
            backup_file(config.TORRC)
            safe_write(config.TORRC, ''.join(new_lines))
    except Exception as e:
        # let caller handle logging
        raise


def get_ports_info():
    info = []
    try:
        with open(config.TORRC, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if re.match(r'^SOCKSPort\s', line, re.IGNORECASE):
                    parts = line.split()
                    if len(parts) >= 2:
                        info.append(f"SOCKS5 proxy: {parts[1]}")
                elif re.match(r'^HTTPTunnelPort\s', line, re.IGNORECASE):
                    parts = line.split()
                    if len(parts) >= 2:
                        info.append(f"HTTP proxy: {parts[1]}")
                elif re.match(r'^ControlPort\s', line, re.IGNORECASE):
                    parts = line.split()
                    if len(parts) >= 2:
                        info.append(f"Control port: {parts[1]}")
                elif re.match(r'^%include\s', line, re.IGNORECASE):
                    parts = line.split(maxsplit=1)
                    if len(parts) >= 2:
                        info.append(f"Bridges include: {parts[1]}")
        if not info:
            return lang_mgr.tr('ports_not_found') if False else 'Ports not found'
    except Exception:
        return 'Error reading torrc'
    return '\n'.join(info)
